libs =
#import libs += libhello%lib{hello}

exe{spirv-tools}: {hxx ixx txx cxx}{**} $libs tools/testscript

out_pfx = [dir_path] $out_root/src/
src_pfx = [dir_path] $src_root/src/

cxx.poptions =+ "-I$out_pfx" "-I$src_pfx"
