import libs = libspirv-tools%lib{SPIRV-Tools}
import libs += libspirv-tools%lib{SPIRV-Tools-opt}
import libs += libspirv-tools%lib{SPIRV-Tools-link}
import libs += libspirv-tools%lib{SPIRV-Tools-lint}

exe{driver}: {hxx ixx txx cxx}{**} $libs testscript{**}

if ($cxx.class == 'msvc')
  exe{driver}: cxx.coptions += /wd4251
